### ISSUE TITLE
Pawns have out of ammo after firing if no bullet in inventory even though charger is not empty

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#82] opened 2017-03-03 07:36 UTC
to reproduce:

 1. pick a loaded weapon
 2. drop all ammo from inventory
 3. shoot

**Comment by RenaudF** [comment] 2017-03-03 07:58
to reproduce:

1. pick a loaded weapon
2. drop all ammo from inventory
3. shoot

**Comment by NoImageAvailable** [comment] 2017-03-03 19:02
Tested, can't reproduce. Can anyone else confirm this issue?

**Comment by NoImageAvailable** [comment] 2017-03-04 08:11
After updating to the latest commit I can now reproduce it on my end. I suspect it has something to do with the recent fix for https://github.com/NoImageAvailable/CombatExtended/issues/64

**Comment by RenaudF** [comment] 2017-03-04 16:19
this affects turrets also, making them totally ineffective

**Comment by Alicecomma** [comment] 2017-03-05 17:29
Fixed in https://github.com/NoImageAvailable/CombatExtended/commit/37d3e61cc3fe23da0382331af500fa5c36478745

**Closed by Alicecomma** 2017-03-05 17:29 UTC
Labels: bug
