### ISSUE TITLE
Explosive building damage.

### ISSUE THREAD

**Issue by Thorbane** [NoImageAvailable/CombatExtended#15] opened 2017-02-09 09:46 UTC
Explosive weapons seem to do excessive amounts of damage to buildings.

**Comment by Alicecomma** [comment] 2017-03-02 06:52
To quantify this, grenades seem to do 200 damage to walls in a 3x3 square around them and much less to other objects.

**Comment by NoImageAvailable** [comment] 2017-03-28 15:31
For reference, a wooden wall has 150 HP, steel 350, granite 595 and plasteel 980. A grenade will blow up a wooden wall, severely damage steel and granite and slightly dent a plasteel wall. Explosives are meant to destroy fortifications so I don't see what the problem is supposed to be.

**Comment by NoImageAvailable** [comment] 2017-05-06 11:46
Since nobody seems to have anything to say on this subject I'm closing this.

**Closed by NoImageAvailable** 2017-05-06 11:46 UTC
Labels: balance
