### ISSUE TITLE
Pack animals cannot drop items from inventory

### ISSUE THREAD

**Issue by RenaudF** [NoImageAvailable/CombatExtended#69] opened 2017-02-27 21:00 UTC
only since I updated today (hadn't updated in a few days..). could be related to #46

**Comment by RenaudF** [comment] 2017-02-27 21:54
somewhere along the way it stopped using ITab_Inventory for pack animals

**Comment by NoImageAvailable** [comment] 2017-03-01 08:42
Probably caused by an XML change removing compInventory from animals. Will test.

**Comment by NoImageAvailable** [comment] 2017-03-01 19:06
Should be fixed in https://github.com/NoImageAvailable/CombatExtended/commit/32fb2cd1b3692fcddfbeef5c21d0086b7436db7f let me know if it isn't

**Comment by RenaudF** [comment] 2017-03-02 09:24
I tried adding
```
      <li>
         <compClass>CombatExtended.CompInventory</compClass>
       </li>
```
to the `Defs/ThingDefs_Races/Races_Animal_Base.xml` file yesterday but that didn't fix it. I'll check when I get home later. Out of curiosity what is the difference with the change in cb30f01:
```
    <inspectorTabs>
...
 -      <li>ITab_Pawn_Gear</li>
 +      <li>CombatExtended.ITab_Inventory</li>
...
    </inspectorTabs>
```

**Comment by RenaudF** [comment] 2017-03-02 19:39
still broken

**Comment by NoImageAvailable** [comment] 2017-03-02 20:43
https://github.com/NoImageAvailable/CombatExtended/commit/79ae9e48fcbca698e507a78bdc310a18f3a73b18 should fix this for good

**Closed by NoImageAvailable** 2017-03-02 20:43 UTC
Labels: bug
