### ISSUE TITLE
System.InvalidCastException thrown when forcing pawn to prioritize hunting animal

### ISSUE THREAD

**Issue by rshackleton** [NoImageAvailable/CombatExtended#371] opened 2017-12-13 23:13 UTC
```
Exception filling window for Verse.FloatMenuMap: System.InvalidCastException: Cannot cast from source type to destination type.
  at CombatExtended.JobDriver_Hunt.get_Victim () [0x00000] in <filename unknown>:0 
  at CombatExtended.JobDriver_Hunt.TryMakePreToilReservations () [0x00000] in <filename unknown>:0 
  at Verse.AI.Job.TryMakePreToilReservations (Verse.Pawn driverPawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.Pawn_JobTracker.TryTakeOrderedJob (Verse.AI.Job job, JobTag tag) [0x00000] in <filename unknown>:0 
  at Verse.AI.Pawn_JobTracker.TryTakeOrderedJobPrioritizedWork (Verse.AI.Job job, RimWorld.WorkGiver giver, IntVec3 cell) [0x00000] in <filename unknown>:0 
  at RimWorld.FloatMenuMakerMap+<AddUndraftedOrders>c__AnonStorey14.<>m__0 () [0x00000] in <filename unknown>:0 
  at Verse.FloatMenuOption.Chosen (Boolean colonistOrdering) [0x00000] in <filename unknown>:0 
  at Verse.FloatMenuOption.DoGUI (Rect rect, Boolean colonistOrdering) [0x00000] in <filename unknown>:0 
  at Verse.FloatMenu.DoWindowContents (Rect rect) [0x00000] in <filename unknown>:0 
  at Verse.FloatMenuMap.DoWindowContents (Rect inRect) [0x00000] in <filename unknown>:0 
  at Verse.Window+<WindowOnGUI>c__AnonStorey0.<>m__0 (Int32 x) [0x00000] in <filename unknown>:0 
```

The animal was a downed caribou in this case.

**Comment by NoImageAvailable** [comment] 2017-12-14 17:09
I can't reproduce this. Implemented a potential fix in https://github.com/NoImageAvailable/CombatExtended/commit/2e0d67e67230b39a639338ba8432fe58cd3fcca6 but no way to test, so let me know whether the issue persists.

**Comment by NoImageAvailable** [comment] 2017-12-25 21:14
Gonna assume this is fixed now

**Closed by NoImageAvailable** 2017-12-25 21:14 UTC
