### ISSUE TITLE
Impossible to hit pawns in doors / shooting through corners

### ISSUE THREAD

**Issue by Alicecomma** [NoImageAvailable/CombatExtended#358] opened 2017-11-22 18:18 UTC
FROM DISCORD (papa_borov#4548):

_When pawn stands in the doors, it is almost impossible to shoot him. Even from zero range._

_As, for example, here_
_2 magazines from usas-12,_
_1 hit._

![image](https://user-images.githubusercontent.com/4662406/33143242-99742e42-cfb9-11e7-8a89-a48b4ab282f5.png)

_Also there was another one bug with shooting through the corner of a wall, but i am unable to reproduce it now._

**Comment by Kai-Holmes** [comment] 2017-11-24 01:20
I think that would be by design. At that range I think melee would be the go to, especially because if you're within arms reach you'd struggle for whatever weapon they had.

**Comment by NoImageAvailable** [comment] 2017-11-24 08:08
First guess here would be that the door is being treated as cover that the target pawn is standing on for collision purposes and it somehow screws up targeting/collision calculations

**Comment by frenchiveruti** [comment] 2017-11-24 14:20
@Kai-Holmes I think that someone tested that with pistols and had the same results.

**Comment by Nianor** [comment] 2017-11-29 07:15
Can confirm, I've had this issue is A17 previously, and it was obnoxious. I don't remember the details exactly, but I believe I had an enemy in a doorway who was attacking one of my melee units, and a ranged unit who was firing a combat shotgun at him point blank. He didn't take a single hit from the shotgun until the shooter had completely destroyed the door. I think this happened a couple other times, too. I'd assume this isn't a feature, as this is more or less the exact situation that combat shotguns are designed for.

**Comment by Alicecomma** [comment] 2017-11-29 18:51
My guess is that the hitbox calculations for buildings don't take into account whether doors are opened or closed.

**Comment by michail-r-borovoy** [comment] 2017-12-24 10:34
Little bump for this issue:
Any shoot maked while shooter or target stands in the doorway never hits the target, hitting the door itself instead.
Any shooting throw the open door is impossible.
It is very, very annoying thing, destroying many tactical possibilities, so i will be very glad if you will pay your attention at it.
Thank you.

**Comment by Alicecomma** [comment] 2017-12-30 22:55
The game treated doors as having a shotHeight the same as walls. You couldn't shoot over walls due to the target behind it being non-visible, but doors are ignored for visibility checks so the game treated the door as an obstacle the size of a wall. Projectiles "shot over" the door would hit the ceiling above the door. Projectiles accidentally shot into the door by skewing factors would hit the door since it was considered a wall for collision purposes as well.

What I changed in #400: door hitboxes and shotheights are treated as if it's a floor when the door is open.

**Comment by NoImageAvailable** [comment] 2017-12-31 15:12
Fixed now

**Closed by NoImageAvailable** 2017-12-31 15:12 UTC
