### ISSUE TITLE
slingshot pellets for a bandit camp reward 

### ISSUE THREAD

**Issue by lucyfareEM** [NoImageAvailable/CombatExtended#622] opened 2019-01-20 16:10 UTC
A friendly faction offered 500 sling pellets as a reward for taking down  a bandit camp but the problem is the slingshot doesn't exist

**Comment by NoImageAvailable** [comment] 2019-02-21 15:28
The issue is reward generation just looks for anything with a sufficient market value and presumably counting disabled CE ammo as it is sellable. Could just change it to be invalid for trading since that mechanism was really only meant to get rid of unwanted leftovers on mod list changes, but they already self-destruct so it's redundant.

**Comment by NoImageAvailable** [comment] 2019-02-21 15:44
Should be fixed in https://github.com/NoImageAvailable/CombatExtended/commit/1efe8c21a37903317ccc013976ed5601997cb9c8 do let me know if this happens again

**Closed by NoImageAvailable** 2019-02-21 15:44 UTC
Labels: bug
