### ISSUE TITLE
Freeze and crashes when hunting "boom" animals with beanbag rounds.

### ISSUE THREAD

**Issue by zozilin** [NoImageAvailable/CombatExtended#681] opened 2019-03-01 12:57 UTC
Pawns will usually try to kill "boom" animals from distance, but with nonlethal beanbags they can't seem to do it and stand in place instead after they down such an animal. Game stops responding for a few seconds in short intervals and eventually crashes if rounds are not swapped or hunt job is cancelled.
[log.txt](https://github.com/NoImageAvailable/CombatExtended/files/2919458/log.txt)

**Comment by NoImageAvailable** [comment] 2019-03-01 15:05
Not related to beanbags, duplicate of #623

**Closed by NoImageAvailable** 2019-03-01 15:05 UTC
Labels: duplicate, invalid
