### ISSUE TITLE
Strange visual issue.

### ISSUE THREAD

**Issue by Thinereapist** [NoImageAvailable/CombatExtended#251] opened 2017-06-16 06:13 UTC
When hunter is firing and Visibility of roofs is enabled the visibility flashes off until projectile ends flight.

**Comment by NoImageAvailable** [comment] 2017-06-16 23:49
Can't reproduce this. What are the exact circumstances this occurs in?

**Comment by Thinereapist** [comment] 2017-06-18 05:57
I'm working on finding exactly what's causing this issue. Likely not CE.

**Comment by NoImageAvailable** [comment] 2017-06-24 07:21
Since OP hasn't replied I'm assuming this is fixed, closing

**Closed by NoImageAvailable** 2017-06-24 07:21 UTC
