### ISSUE TITLE
Null ref exception on out of ammo

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#64] opened 2017-02-27 08:53 UTC
As raiders run out of ammo they throw a null ref exception. Tested with tribal archers, might be something specific to bows, needs some more testing still.

**Comment by Alicecomma** [comment] 2017-02-27 20:13
This also happens using frag grenades and manual aim-shooting multiple times for the same (final) grenade in the inventory.

**Comment by Alicecomma** [comment] 2017-03-02 06:46
This issue may have been fixed in https://github.com/NoImageAvailable/CombatExtended/commit/74cdc8a4cad2e6ff9a16529a20a60960dea09329, where it is fixed for grenades. Please report whether the issue is still there.

**Comment by NoImageAvailable** [comment] 2017-03-02 15:52
Bug persists for archers

**Comment by Alicecomma** [comment] 2017-03-02 21:43
Resolved bug for bows + grenades in https://github.com/NoImageAvailable/CombatExtended/commit/1274021d198af473dcd714aad200f124e2b73017.

**Closed by Alicecomma** 2017-03-02 21:43 UTC
Labels: bug
