### ISSUE TITLE
Ammo on the ground continually fires in random directions

### ISSUE THREAD

**Issue by Lurmey** [NoImageAvailable/CombatExtended#281] opened 2017-07-18 16:46 UTC
With Crash Landing, when CE ammo crashes down to the planet the rounds fire at random as if they're on fire even if they're not burning. They continue to fire even after being picked up by a pawn and placed into their inventory until there's none left and errors appear when attempting to haul them.

This issue fixes when the save is reloaded, unless the ammo is actually on fire.

Logs including restart (Seems to be some errors from another mod in there too): https://gist.github.com/6d85a89a20df524108841eafcc35afbd

**Comment by NoImageAvailable** [comment] 2017-07-22 23:28
That looks like an issue with some other mod messing with bills/jobs, can you reproduce the issue with just CE loaded?

**Comment by NoImageAvailable** [comment] 2017-08-19 11:08
No reply in almost a month, closing

**Closed by NoImageAvailable** 2017-08-19 11:08 UTC
