### ISSUE TITLE
"Make grenades until x" counts stacks instead of items

### ISSUE THREAD

**Issue by Maeyanie** [NoImageAvailable/CombatExtended#168] opened 2017-05-08 12:06 UTC
Testing on v0.3.0-beta

I created a job to make frag grenades, set it to "do until you have x" and left it on x = 10. By the time I noticed, there were 40 grenades in the stockpile, and it said 1/10.

Further testing shows that it seems to be counting stacks of items, rather than individual items. The same thing happens with all other thrown grenade type weapons, but does not appear to happen with mortar or cannon shells.

**Comment by NoImageAvailable** [comment] 2017-05-08 13:19
Looks like this is caused by grenades not having the <resourceReadoutPriority> set in their def. Will add `<resourceReadoutPriority>First</resourceReadoutPriority>` to GrenadeBase in the next commit.

**Comment by NoImageAvailable** [comment] 2017-05-09 12:06
Should be fixed with PR #170

**Closed by NoImageAvailable** 2017-05-09 12:06 UTC
Labels: bug
