### ISSUE TITLE
Error after loading a save

### ISSUE THREAD

**Issue by pardeike** [NoImageAvailable/CombatExtended#740] opened 2019-08-03 15:13 UTC
While debugging amputations with Zombieland (not related to this issue), I have a save game that produces this error during loading:

```
Exception in SetupToils for pawn Tom driver=JobDriver_Reload (toilIndex=0) driver.job=(ReloadWeapon (Job_11503) A=Thing_Human161 B=Thing_Gun_LMG41621) lastJobGiver=null
System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.GenGrid.InBounds (IntVec3 c, Verse.Map map) [0x00000] in <filename unknown>:0 
  at RimWorld.MoteMaker.ThrowText (Vector3 loc, Verse.Map map, System.String text, Color color, Single timeBeforeStartFadeout) [0x00000] in <filename unknown>:0 
  at RimWorld.MoteMaker.ThrowText (Vector3 loc, Verse.Map map, System.String text, Single timeBeforeStartFadeout) [0x00000] in <filename unknown>:0 
  at CombatExtended.JobDriver_Reload+<MakeNewToils>d__23.MoveNext () [0x00000] in <filename unknown>:0 
  at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:SetupToils()
Verse.AI.JobDriver:ExposeData()
Verse.PostLoadIniter:DoAllPostLoadInits()
Verse.ScribeLoader:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow(String)
Verse.Root_Play:<Start>m__0()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```

**Comment by LockdownX7** [comment] 2019-08-03 15:17
Duplicate of  #719, it's fixed in the dev build.

**Closed by LockdownX7** 2019-08-03 15:17 UTC
Labels: duplicate
