### ISSUE TITLE
A18: Exceptions thrown during siege

### ISSUE THREAD

**Issue by rshackleton** [NoImageAvailable/CombatExtended#374] opened 2017-12-14 23:04 UTC
The following exceptions are thrown constantly when a siege triggered. They started once the mortar had been built. Could be related to other mods but I've yet to check.

```
Exception in BreadthFirstTraverse: System.InvalidCastException: Cannot cast from source type to destination type.
  at RimWorld.JobGiver_ManTurrets+<TryGiveJob>c__AnonStorey0.<>m__0 (Verse.Thing t) [0x00000] in <filename unknown>:0 
  at Verse.GenClosest+<RegionwiseBFSWorker>c__AnonStorey1.<>m__1 (Verse.Region r) [0x00000] in <filename unknown>:0 
  at Verse.RegionTraverser+BFSWorker.BreadthFirstTraverseWork (Verse.Region root, Verse.RegionEntryPredicate entryCondition, Verse.RegionProcessor regionProcessor, Int32 maxRegions, RegionType traversableRegionTypes) [0x00000] in <filename unknown>:0 
  at Verse.RegionTraverser.BreadthFirstTraverse (Verse.Region root, Verse.RegionEntryPredicate entryCondition, Verse.RegionProcessor regionProcessor, Int32 maxRegions, RegionType traversableRegionTypes) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.RegionTraverser:BreadthFirstTraverse(Region, RegionEntryPredicate, RegionProcessor, Int32, RegionType)
Verse.GenClosest:RegionwiseBFSWorker(IntVec3, Map, ThingRequest, PathEndMode, TraverseParms, Predicate`1, Func`2, Int32, Int32, Single, RegionType, Boolean)
Verse.GenClosest:ClosestThingReachable(IntVec3, Map, ThingRequest, PathEndMode, TraverseParms, Single, Predicate`1, IEnumerable`1, Int32, Int32, Boolean, RegionType, Boolean)
RimWorld.JobGiver_ManTurrets:TryGiveJob(Pawn)
Verse.AI.ThinkNode_JobGiver:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
RimWorld.ThinkNode_Duty:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
RimWorld.ThinkNode_JoinVoluntarilyJoinableLord:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob_Patch1(Object, JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

```
Exception in Verse.AI.ThinkNode_Priority TryIssueJobPackage: System.InvalidCastException: Cannot cast from source type to destination type.
  at RimWorld.JobGiver_ManTurrets+<TryGiveJob>c__AnonStorey0.<>m__0 (Verse.Thing t) [0x00000] in <filename unknown>:0 
  at Verse.GenClosest+<ClosestThingReachable>c__AnonStorey0.<>m__0 (Verse.Thing t) [0x00000] in <filename unknown>:0 
  at Verse.GenClosest.ClosestThing_Global (IntVec3 center, IEnumerable searchSet, Single maxDistance, System.Predicate`1 validator, System.Func`2 priorityGetter) [0x00000] in <filename unknown>:0 
  at Verse.GenClosest.ClosestThingReachable (IntVec3 root, Verse.Map map, ThingRequest thingReq, PathEndMode peMode, TraverseParms traverseParams, Single maxDistance, System.Predicate`1 validator, IEnumerable`1 customGlobalSearchSet, Int32 searchRegionsMin, Int32 searchRegionsMax, Boolean forceGlobalSearch, RegionType traversableRegionTypes, Boolean ignoreEntirelyForbiddenRegions) [0x00000] in <filename unknown>:0 
  at RimWorld.JobGiver_ManTurrets.TryGiveJob (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn, JobIssueParams jobParams) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn, JobIssueParams jobParams) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
RimWorld.ThinkNode_Duty:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
RimWorld.ThinkNode_JoinVoluntarilyJoinableLord:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob_Patch1(Object, JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

**Comment by rshackleton** [comment] 2017-12-14 23:17
> AAAAA - Today at 10:54 PM
> enemies still spawn with the old mortar shells instead of 81mm shells, which they're unable to utilize in the 81mm mortars, causing errors during sieges as mortarmen can't initiate their job

Looks like AAAAA figured out why this is happening!

**Comment by NoImageAvailable** [comment] 2017-12-15 09:43
This has nothing to do with shells, the error is due to the vanilla JobDriver trying to typecast Building_TurretGunCE into Building_TurretGun.

**Comment by rshackleton** [comment] 2017-12-23 00:45
Was looking into this but cannot figure out why a Harmony patch isn't being executed.

https://github.com/rshackleton/CombatExtended/blob/siege-bug/Source/CombatExtended/Harmony/Harmony-ThingDef_IsShell.cs

The `ThingDef.IsShell` property is called in this patch which is being executed.

https://github.com/rshackleton/CombatExtended/blob/siege-bug/Source/CombatExtended/Harmony/Harmony-TurretGunUtility.cs#L60

Would appreciate you looking at this and seeing if you can understand why the patch isn't working - I've hit a wall with it.

**Comment by rshackleton** [comment] 2017-12-27 00:05
Ok, fixed most of the issues in this branch now.

https://github.com/rshackleton/CombatExtended/tree/siege-fix

The remaining issue is that once they tend to spawn with incendiary and HE shells, they only use the HE shells and no extra shells spawn once the HE stack is depleted.

If I destroy the incendiary stacks with the debug tools then more shells are spawned in.

Either we need to only allow HE shells to spawn or we need to adjust the AI to use the incendiary shells too.

**Comment by NoImageAvailable** [comment] 2017-12-27 19:42
The issue is due to the way the CE ammo selection works, it'll only accept whatever ammo type is selected for the mortar. Needs to be changed to either allow any ammo on NPC turrets or automatically switch the selected type when it runs out.

**Comment by NoImageAvailable** [comment] 2017-12-31 10:19
Fixed in https://github.com/NoImageAvailable/CombatExtended/commit/10e498a32fd8976b45a7501e87eed77075ecc846

**Closed by NoImageAvailable** 2017-12-31 10:19 UTC
Labels: bug
