### ISSUE TITLE
Animal Training

### ISSUE THREAD

**Issue by wlwest2** [NoImageAvailable/CombatExtended#269] opened 2017-07-09 06:12 UTC
Most of the time training an animal works just fine but every once in a while my pawns get stuck.  The assigned pawn for handle just stand on top of a pile of Kibble and will not do anything else until they are removed from the Handle job.  

I have attempted to get them to top the kibble (they have picked it up) and they just pick it up again.  My latest example has picked up 21 kibble with both bulk and weight still allowing them to pick up more.

**Comment by wlwest2** [comment] 2017-07-09 06:13
I love the mod by the way.

**Comment by NoImageAvailable** [comment] 2017-07-09 08:06
Are you using the outdated Steam version?

**Comment by wlwest2** [comment] 2017-07-10 06:50
No, all up to date.  Some more info.  I forced my pawn to pickup 30 kibble and he is able to work as expected.  I think the issue here is that the 21 kibble would take the bulk/weight to its max on the initial calculation.  I am not sure the load outs are taking into consideration the load bearing items.

**Comment by NoImageAvailable** [comment] 2017-07-10 07:23
So in the about text it says v1.4? Only known bug causing this has been fixed a few versions back and I haven't had any reports of this behavior nor have I seen it myself in testing since then, so I'd like to make absolutely sure you're not using profugo's no longer updated Steam version, which is still stuck on 1.1.

**Comment by NoImageAvailable** [comment] 2017-07-17 17:29
No reply in a week and I can't reproduce this, closing

**Closed by NoImageAvailable** 2017-07-17 17:29 UTC
